apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-openstack
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgBA6gMkDAKLPkeaD/NH1NSLcALmOl+LPBRspurgOVn4ZxI8kET95zrQbhWLlR6/2uhxx7slNfeOyZl7TZo8TeM0W1L5QV56zNacJxHa3swTiuFSLnaF/nr+sH259d8gyIrL7RlY7M1vtOBa5JuY7Sv2aUOWAiBAr3F0n75n/xVe7e4QKviJPthQhIKE0OvOy7bkvlRowSzNnv6lh5ZKryaQzXukK9FB7wEvoFmpgaQPXxCgMJN7MqSGCGpaihNupk9dinEDPD7UGgyKuvOAvyP2VjyyM6rPEQ0VjGXohyFEU6m8S7IKt7cUgCOnIzh8N/UVn92q6GOet1S4LqzYa/WeqWoatHhw3bLubQMorEi8urYmETYiInhT7wHUSb5yA1RzhzoaOcbFYU7APSXQ2MsnTkP+IhNs9dAGykHf3GNi9rufZnkQ2bNwu31uXb7AJ5mp/thv063SIuZ0CdlNEdZF3IchHlV7/5ly1EDkgnoswmrYX5NFiX8LWKJEYoQWBRvuvFp7bB6hKlt8Bd6RflTQdktC/UhUVeQRyeBjGUHpniMK0UK79Vu1Sri8WRqX/vClW5h9udTjFHT+4T2Oy50doECnF2lpoyEPZO2qFk5BqvceBQdQrInZ4T0Yr3BDib9mJt+swjxpzU4RRxZsQ5Mds8lsdkTOY44bUCCJIoKDao/r4f8obB5VSKr3lEYxxRfAEPQrqzPJVquhCvdmosEmXbOxuXwXYCHA2xkYK1Xx5SK6JSiiGK6xQgqJdb05O6CQ34gVI5NNzmCfJxKF2URJInuBWSP84mvhrWPxiQW5d8wmPBVmznxt+zE2ncuCzSqgv1pI+vKpiC9BVQ+v/xA3hSb7BBM9cAS/6g/++IduodjrNUSTEOz5actGxBjovaW1YEvE4qc+cEbIe1ksjtSJ5hdcL2gq4zGhqi4lDO27QU7ERRswS/AwaT29gdEk/g95POTHRa91KJ5mUOg2vKzqPItWKLV80/CxXwzSMJlK7euNthMoagBL9ma/wYJltwqoYWpfN+kYSt6Y5HbyBctyOxXkSRFagoDYJjFhmHt9AY5E0Y6KUGaQHv+PxHnmTcUpVtpaLAkvreOJ2U1vTTMsCwHc1kzDq+Rw7yapofqFotm55w6XAABUQzkilqhtHkGGYXK1doRBakJu3r1YI7kFQvnEC+m91SJmpat08AUubYEHT/C4Ao7pIZQxOTBi8F7w49u2ybY6vzJzCU2XhOKvP5ex/ha7KFDAAPIculxD2QuyBwnbr1D7nE0lXWuAWjCgiGjjkYmO+m+Qlm0FUzNyXAeCjEAbM0tin0nppdfDnQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        addons.stackhpc.com/watch: "true"
      name: demo-openstack
      namespace: capi-self

