apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-caas-mgmt-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgA61utSrV0xZ805LjiTNKzpOaP3EY73/iTa0HbnYCztZktgKnHKugRZemIv3XklLhjHl96Vi0ZkSJ9//7lGy3EW5dRrGv1//QXufoCqOKlfORcV0McQMMoQtp7WRiXOV8S9jwjwPOLgCIksXMy95+YkfCvDXms/03Xj17uRk1bbK9Lspi1NmOw8Uqyjaim7dIBdY/jg4e2VqYJHUrpwZzPsBERcGJqf3t5V7dpkqDCFUaO/1ZjWvntHwq4r9C22L/D4SbUGFvXwnwZgPBSp8AnKH4Za1XPxXEnDTOZxlJqDSdT65fKK/eZN5EhSBn3PG/TSxAe5n3/2pFipgDeIdlB5imQA+rM6uJXqsA4FGdEdv+AwM8231unLaFCcTMRVgmSjsgy1eU3ZiyXP97ORG45NolB2oXiydcarBEONUUig/dswyZd9Gac8TP8dgZ1tuZ66zxnOVA5M/mBz8xnlMeejCMCJkEn8VV2FU7Sh+KCPa9L5k99e3spxSsDViNTkpaW5Mx69j7u1dTPyzTPb5+yRfuvCle0QyFgINO0oqHpDyVq+IdtWdghLK0A5aW8FxIL1w76O27O6GXXKfxeUCAhmnYHO9+WjPqoSaau+4GeVY5o5Evk6vNDEFN0JYIsWkxZjYKtlAB/UF+CnM8uPbzPtrQs+/rJEYYvgW8BTVOeYvkP/3tPPLxxpYe3l4jIp6K389WgM39qnQT/naSbL1rmYacv1ouJsPsnPHT6ppNdGHpkT7f6NczpyGhNMUno259f5W2OXe47dGf6VPd1LMVwoPe5sBIrJNQk4S/7ciPWULCsU8t2mYnKVc2Obol0L5Bw2h2p0SiUVR/Kh/PhfZSG/s7Dp+jspEBfpqHyvo6Qh6vS28Zm6uZjHmDN1M+j3N7St1cXAjsd0Hn96h7XbNLcasfRxPNbK932cgEyLDFHJ0+neZ7ft/N8gIbC9mGchLboWopS+r7wOLMg9Hu+HakxSJlPUxbpXi+nISkKjxdh3Is2WIncoBIqncyXUD16a2NULYcZKuYCLq9TY7qc3xmNYQuMTerLeywaNLhF3zlCKbnwiub96DsLgW/IlNanrB8+fvZU9Z0mkgRc6LDvkZUV5M3lgbGuIs+5wE21j2TXu7qvHwpFKN5owW4CFmIbPlKeMkJTCLiuDk04YNHv+o2EdngInFzR00pcRnGawBBAj3nEh22FXdFk6gpAju1OkLdjAj4dAAaquRD35sPOqvorht/1jZnwjZ//l/YhU4ybYuNYUQVmsWdRKzbSWGmvXQ/ztLmNKMrz9KYicdrug0AYckuiY2OW10mVDb1zftmFD8Q==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        addons.stackhpc.com/watch: "true"
      name: cluster-caas-mgmt-credentials
      namespace: capi-self

