apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-caas-mgmt-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgAzOuOKY46olS4azIzU7reFi8JL0YGMo6j71Fz+sDfWbg1Eawke2qcuhwLt33c+lN0XFCHKJjPadeJtLjTeGpJ4BdrW6QMuGe/D+HWg7Ut20/HEUbrpqNfOXxc1MJNrxMMg0Ns43Zcr0WNNsKsU5ejBO5HP0vfDPSXNLZIWw9s2vpSSopXQ6uveA0S8zVaGxKVIM0OKpOANrjlJhS0TnXNROxGeUPA5Xrqly038CW19UxoibkP4motCE6EW5DmSDkfXw5tAerJ7RZPV0IuBgdBrwvs6JhDjlECPSPCWYGTnmv78heMdlMToFP8AU4yCtRa7lDEWi/ghA46MfM/LKiJ/ox9jcXZufuAo4L2t3jwnKLb5PbWfw/Hh2VuDP8tloIO+V4MVlI/Fvoh+/sajOvP5X6HUECjEc8Thn1RSNGvOZGi9e4moLoJk5SSZDBIY5h+YBwfRt2fIQl75shR/YuUtiXjOXC3frcaaIphr+4BzuausKFR1vDUOru+vnE6IGLlHAlC2nj/h9wfRN9GtcByw0cxMjvUdjKf9vElrULAcm+C40lR4nV4GBNYuKiJy7CnI0ha/A9LhbzkCOjtgVDCu5ueirlIM1opRXM3UfDRfOny0ePxZ+0RP4RvUqKX0hk6C6Upg0xW1JPZn3XGkOmIVpIARue/Fcw+QH91H7vXDmjxr2LMYYZVK7xr6iYxSP7GEVnSEK6U6qqKDAMIj86t+vuzmsy5wytUWAkbNTMXur1SVvD5oG/iIffsZkP1LLWyy8yeyXz92KZRc8/Lrqtsj7k20O3c++ggpO7z2oWv2CwZn4JeUsdRrePS53p9HQcj4BBHgY6ZjSPX8kc4LotMmecJWQ8SJ9XwPOMulENzJgT4N+7FteHh05+YKZqejwxmpkWIDOfWifw8B8Oj7etFwNwcPhijRO/Cbe+9FNiJHeb9Jqd/e/c2WxtEEGkidLO/FTY94HmVdoJpsUVcVuw+Xo0Pp5cdvSySlVWdrOxHkLRGUt6EtjZW/XCc6hrXX5U2GS4zydrZ+cjc0QDr50X7ydEaoAXZIjzp0B5K/VH2HUab3Vp9fzcD9NYopWRLeyqP64XBCRC2AZBmDR/oiRToxLgxWmvMl8ODCRZf/0/r1AZuoAU4n56uwt5U/zzkfGi/U633s4iOGzWU0qLikM5LvBddewxmSsJxxyBhGZjpDiEzdlnau509//urD61PKv36kK1yyb/DoyE6RJVtf1iisdgiJkuFEvmd5Svr1u1bhBTZt8doNMYwv6OQSArxdTT+/p6XDQYkTSznz0Pg9ITdSRS+FZrC4+ccStzOPrCaVzg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        addons.stackhpc.com/watch: "true"
      name: cluster-caas-mgmt-credentials
      namespace: capi-self

