apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-caas-mgmt-credentials
  namespace: capi-self
spec:
  encryptedData:
    clouds.yaml: AgBZPBHAu+/6Z5ypksCQDuctLSh54ByI1oZDNEOEVURtVwpHeR2AcAq1fd6tOzrv1bGGvQrxQTkgFEN4fGke+899BN/1W2TcOr3/viwzTAig1rSqdbeelyXurl+NmgX/9KliN8mcV3G+Pmu5aE9kl4gZH3OEkv73DIDykc4uPS+vJJ429yl5Gw6Q4YR5n3fxKe2KPN0XPLWauxWMQYiQKc7euMSZX+ksgtComMp0tjUeqj5UYkocViioWJ8J0dRV1g8FbsfJoIgDjtRLTfYrUcEe3uRqxYEtRinf/Q4donSPwITH16BPBSvfPpTkYgR0veMesd06+eYwKPmYEGFfWZSU2pENogDcG7qvsJUZcjKDSov+Du7eBZKI7iGHzhKcM4XjHq1fEqQPycL1PNdGmY8lWrgfoGORQ0gGZ8h2BmBJqlOP+1h0uQ8zNSHqCHW3220iEqTW0r+5rykUgSwVGLvQgA4/5J/vwpcZnBPCjMM7wJBIOsAqXKLqc0EA1IRne7ToLNR3rUyryxpSFlM9MuDFy9UVPkiQCf8I9jPdp0ZmXn62tKwqkqgZUbqg2eYJtCLP6nnLF7F9K5BzL96NAbNcPfRI4IT4/N9/u/2mKwDQ9HxSVONPUqzasFAADWBrkhUg3ryczfyzzqmh/hP3ogJhjoOFsRipo+7cmjOxSzk0KqIPMW6McbQ5zBvOZKpZBUMvBR/vDtoAaB2h2poiXJqlKK6qYEm6dZCkWwLb0oSDi3NO10oifu7Hf1gAwMs2guuZDMRh0VPVYPmDA1eNplJbsYUkh8dLyKBNbxx/olW/w71XrhiZqouraKY2lQ6w/3KpuAdsuFPwR4nqCXFgOThZPCR2FxoIGw+CC6FWjU5geXxuH6fvXSu96KxqzGboxK8HjBzz5ZSHzsCHCLReE4jfZYBMFN8qEKIOO/WrPLiDHQ+jCtHoV7h+MX3+NKdQKmzXvrZnkzi5WCRoflofexI5NjUlWo428IjEGQnjxclnz1K2De+T4BTUPW0h4OF8tKkgklfdiDe5QvGxaTl3FpDK4kSEoOKqagrrLCtZ7YMxO6nNAMqP30JK36tCIEM4hbIpBkMP/ON4S4CdC583TN6XTq1YbNCCNIwc2lk9+MIdvgbGjAYZrJsCftD25lrjPS1n2MtPRRGCDya+G45D/lq/GYHPAn3GfvlKutkxEupt4rh+267tNH+6Rx6gQaCU2qn3EH5hTHlLAN9n10wqN+t31mtKkkXtUiIGcO9m145rgtFPsFE2aDuRa9+NC+cljN1PyKTYA5iPcuLFvPxc+OhEaBkqg13U04D8C7HUs2dj6w==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        addons.stackhpc.com/watch: "true"
      name: cluster-caas-mgmt-credentials
      namespace: capi-self

